name: Check vaccine availability

on:
  schedule:
    - cron:  '0,15,30,45 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: npm install
      run: npm install

    - name: check availability
      run: bin/check